---
- name: add zerovm repo
  action: copy src=../files/zerovm-precise1.list dest=/etc/apt/sources.list.d/zerovm-precise.list owner=root group=root mode=0644
  tags:
    - prereq

- name: add zerovm repo key file
  action: copy src=../files/zerovm.key dest=/root/zerovm.key mode=0644
  tags:
    - prereq

- name: add zerovm repo key
  action: shell apt-key add /root/zerovm.key
  tags:
    - prereq

- name: ensure apt repo is up to date
  action: apt update-cache=yes
  tags:
    - prereq

- name: add build-essential package
  action: apt pkg=build-essential
  tags:
    - prereq

- name: add all zerovm packages
  action: apt pkg=$item
  with_items:
    - zerovm
    - zerovm-dev
    - nacl-sdk
  tags:
    - install

